[package]
name = "rns-mavlink"
description = "Reticulum Mavlink bridge"
version = "0.1.1"
license = "MIT"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["json"] }
axum-server = { version = "0.8", features = ["tls-rustls"] }
bytes = "1.*"
chrono = "0.4.*"
clap = { version= "4.*", features= ["derive"] }
ed25519-dalek = "2.*"
env_logger = "0.11.*"
log = "0.4.*"
mavlink = { version = "0.17.*", features = ["std", "common", "serde"], default-features = false }
rand = { version = "0.10.*", features = ["chacha"] }
rolling-file = "0.2.*"
rusqlite = { version = "0.31.*", features = ["bundled"] }
rustls = { version = "0.23", features = ["ring"] }
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
tokio = { version = "1.*", features = ["full"] }
tokio-serial = "5.*"
tokio-util = "0.7.*"
toml = "0.8.*"

[dependencies.kaonic-ctrl]
git = "https://github.com/BeechatNetworkSystemsLtd/kaonic-radio"
version = "0.1.*"

[dependencies.kaonic-gateway]
git = "https://github.com/BeechatNetworkSystemsLtd/kaonic-gateway"
version = "0.2.*"

[dependencies.kaonic-reticulum]
git = "https://github.com/BeechatNetworkSystemsLtd/kaonic-gateway"
version = "0.1.*"

[dependencies.radio-common]
git = "https://github.com/BeechatNetworkSystemsLtd/kaonic-radio"
version = "0.1.*"

[dependencies.reticulum]
git = "https://github.com/BeechatNetworkSystemsLtd/Reticulum-rs"
version = "0.1.*"

# patches pin version to fix radio config timeout error
[patch."https://github.com/BeechatNetworkSystemsLtd/kaonic-radio"]
kaonic-ctrl = { git = "https://github.com/spearman/kaonic-radio", rev = "3abf34ec5c4a57bdaa41c3b9ab12df7db03496a0" }
kaonic-frame = { git = "https://github.com/spearman/kaonic-radio", rev = "3abf34ec5c4a57bdaa41c3b9ab12df7db03496a0" }
kaonic-net = { git = "https://github.com/spearman/kaonic-radio", rev = "3abf34ec5c4a57bdaa41c3b9ab12df7db03496a0" }
radio-common = { git = "https://github.com/spearman/kaonic-radio", rev = "3abf34ec5c4a57bdaa41c3b9ab12df7db03496a0" }

[patch."https://github.com/BeechatNetworkSystemsLtd/kaonic-gateway"]
kaonic-gateway = { git = "https://github.com/spearman/kaonic-gateway", rev = "af4940a97fb290be80c83303f15966db2a08e4c1" }
kaonic-reticulum = { git = "https://github.com/spearman/kaonic-gateway", rev = "af4940a97fb290be80c83303f15966db2a08e4c1" }
kaonic-vpn = { git = "https://github.com/spearman/kaonic-gateway", rev = "af4940a97fb290be80c83303f15966db2a08e4c1" }

[patch."https://github.com/BeechatNetworkSystemsLtd/Reticulum-rs"]
reticulum = { git = "https://github.com/spearman/Reticulum-rs", branch = "main" }
